# -*- coding: utf-8 -*-
"""edge_week7_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xrSpRWN0L1Y34Vuu1Uw-tviAwttgAkZG
"""

import pandas as pd
import numpy as np

df= pd.DataFrame(
    {
        'Category': ['A','B','A','C'],
        'Value': [10,20,15,30]
    }
)
df['Category'] = df['Category'].astype('category')
print(df.dtypes)

df.eval('new_value = Value * 2', inplace=True)
df_filter = df.query('Value>40')
print(df_filter)

arrays = [
 ['A', 'A', 'B', 'B'],[1, 2, 1, 2]
 ]

index = pd.MultiIndex.from_arrays(arrays, names=('Group', 'Num'))
df = pd.DataFrame({'Values': [10, 20, 30, 40]}, index=index)
print(df)
print(df.loc['A', 1])

df = pd.DataFrame({
 'Category': ['A', 'A', 'B', 'B'],
 'Type': ['X', 'Y', 'X', 'Y'],
 'Value': [10, 20, 15, 25]
 })

pivot_df = df.pivot_table(values='Value', index='Category', columns='Type', aggfunc='sum')
print(pivot_df)

df['rolling_avg'] = df['Value'].rolling(window=2).mean()
print(df)

df['expanding_sum'] = df['Value'].expanding().sum()
print(df)

df = pd.read_csv('/content/Historicalinvesttemp.csv')
print(df.head())

df = pd.read_excel('/content/Historicalinvesttemp.xlsx')
print(df.head())

import requests
import json

def get_covid_data():
    url = "https://covid-19-data.p.rapidapi.com/report/totals"
    headers = {  # This line and the following two lines were incorrectly indented.
        "X-RapidAPI-Host": "covid-19-data.p.rapidapi.com",
        "X-RapidAPI-Key": "YOUR_RAPIDAPI_KEY"
    }
    response = requests.get(url, headers=headers)

    # Check the status code
    if response.status_code == 200:
        print("Successfully fetched the data!")

        # Parse the JSON data
        data = response.json()

        # Extract and print specific information
        global_data = data['Global']
        print("New Confirmed Cases:", global_data['NewConfirmed'])
        print("Total Confirmed Cases:", global_data['TotalConfirmed'])
        print("New Deaths:", global_data['NewDeaths'])
        print("Total Deaths:", global_data['TotalDeaths'])
    else:
        print("Failed to fetch data. Status code:", response.status_code)

# Call the function to get and display the data
get_covid_data()

import sqlite3
import pandas as pd

# Connect to the database (or create it if it doesn't exist)
conn = sqlite3.connect('database.db')
cursor = conn.cursor()

# Create the table if it doesn't exist
cursor.execute('''
CREATE TABLE IF NOT EXISTS my_table (
    name TEXT,
    age INTEGER
)
''') #This line ensures the table 'my_table' exists in the database.

cursor.execute("INSERT INTO my_table (name, age) VALUES (?, ?)", ('Alice', 30))
cursor.execute("INSERT INTO my_table (name, age) VALUES (?, ?)", ('Bob', 25))

# Commit the changes to the database
conn.commit()
# Run a SQL query
df = pd.read_sql_query("SELECT * FROM my_table", conn)

# Display the first 5 rows
print(df.head())

# Don't forget to close the connection when done
conn.close()

df1 = pd.DataFrame({'ID': [1, 2, 3], 'Value': [100, 200, 300]})
df2 = pd.DataFrame({'ID': [2, 3, 4], 'Score': [90, 80, 70]})
merged_df = pd.merge(df1, df2, on='ID', how='inner')
print(merged_df)

df = pd.DataFrame({'Date': ['2023-01-01', '2023-01-02', '2023-01-03'], 'Value': [10, 20, 30]})
df['Date'] = pd.to_datetime(df['Date'])
print(df)

